name: noru
description: A CarPool Application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  firebase_auth: ^3.6.1
  firebase_core: ^1.20.0
  firebase_analytics: ^9.3.0
  get:
  get_storage:
  flutter_datetime_picker: ^1.5.1
  flutter_google_places: ^0.3.0
  cloud_firestore: ^3.4.2
  http:
  geolocator:
  geocoding:
  flutter_typeahead:
  google_maps_flutter:
  flutter_switch: ^0.3.2

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/CarImage/



  fonts:
    - family: Playfair Display
      fonts:
        - asset: fonts/PlayfairDisplay-Medium.ttf
    - family: Aboreto
      fonts:
        - asset: fonts/Aboreto-Regular.ttf
    - family: PT Serif
      fonts:
        - asset: fonts/PTSerif-Regular.ttf
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-VariableFont_wght.ttf
    - family: Caecilia
      fonts:
        - asset: fonts/Caecilia-Bold.otf
    - family: OpenSans
      fonts:
        - asset: fonts/openSans/OpenSans-Bold.ttf
        - asset: fonts/openSans/OpenSans-BoldItalic.ttf
        - asset: fonts/openSans/OpenSans-ExtraBold.ttf
        - asset: fonts/openSans/OpenSans-ExtraBoldItalic.ttf
        - asset: fonts/openSans/OpenSans-Italic.ttf
          style: italic
        - asset: fonts/openSans/OpenSans-Light.ttf
        - asset: fonts/openSans/OpenSans-LightItalic.ttf
        - asset: fonts/openSans/OpenSans-Medium.ttf
        - asset: fonts/openSans/OpenSans-MediumItalic.ttf
        - asset: fonts/openSans/OpenSans-Regular.ttf
          style: normal
        - asset: fonts/openSans/OpenSans-SemiBold.ttf
        - asset: fonts/openSans/OpenSans-SemiBoldItalic.ttf



  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
